### ISSUE TITLE
JTAG blocks

### ISSUE THREAD

**Issue by AGenchev** [mwrnd/innova2_4gb_adit_xdma_ddr4_demo#1]
Hello I wonder how do you use the 2 JTAG blocks in this design.
I also put one to see what will happen and it doesn't show when the JTAG is connected to the board and the image is uploaded to the FPGA. So they are not chained to the hardware jtag.

**Comment by mwrnd** [comment]
A JTAG Block connected to an AXI SmartConnect block that has any valid memory mapped (like an AXI BRAM Controller) should show up in XSDB. Refer to [Test AXI Blocks Over JTAG](https://github.com/mwrnd/innova2_xdma_demo?tab=readme-ov-file#test-axi-blocks-over-jtag). My plan is to add a RISC-V core to the design at which point such blocks will be more useful.
```
source /tools/Xilinx/Vivado_Lab/2023.2/settings64.sh
xsdb
```
```
connect
after 7000
targets
target 3
mrd 0x80000000 1
mrd 0x70100000 4
disconnect
exit
```

![xsdb_JTAG2AXI](https://github.com/mwrnd/innova2_4gb_adit_xdma_ddr4_demo/assets/38073881/a3979004-896c-4ebf-93a2-84a077e37bf8)

**Comment by AGenchev** [comment]
Thanks! It seems it works for you. I didn't know I need to use **xsdb** and was looking into Vivado HW manager.
I hooked one to the AXI Smart Connect, connected to DDR4 MIG and tried to read/write the DDR4 via JTAG. 
The DDR-4 was setup with address 0x200000000, size 4G
It returned me:
```
xsdb% mrd 0x200000000 4                                                                                         
       200000000:   DEC0DEE3
       200000004:   DEC0DEE3
       200000008:   DEC0DEE3
       20000000C:   DEC0DEE3
```
It seemingly is trying to tell me that I ask data from the wrong address or probably my JTAG needs to be configured.

I also couldn't grasp PCIe to AXI Address translation: if we set it to 0x40000000, then how we access something with Master base address 0x80000 ? The address we need to request from the PCIe bus becomes negative (0x40000000 - 0x80000).
Also if the "size" is 1M, 0x40000000 + 1MB = 0x40100000, we should not be able to access the BRAM at 0x80000000.

**Comment by mwrnd** [comment]
Did you first write to the DDR? The DDR4 IP Block does not allow reading from uninitialized memory. You may need to first write to the DDR using `dd` or `dma_to_device`. I need to look into this further.

Did you switch to the correct `target`? Just in case, try the other `target`s.

> PCIe to AXI Address translation:
> PCIe bus becomes negative (0x40000000 - 0x80000)

The PCIe to AXI Address Translation offset is meant as a convenience for `M_AXI_LITE`. It has no effect on `M_AXI` blocks. My understanding of the rational behind it is that if you implement a processor or some control system with its peripherals at some address range sequence (0x7001000, 0x7002000, 0x7003000, etc.) you can use the offset to allow [memory-mapping](https://manpages.ubuntu.com/manpages/trusty/man2/mmap.2.html) everything into a small array for easy access to individual bytes.

If you do not see a need for it currently then just set the PCIe to AXI Address Translation offset to 0.

**Comment by AGenchev** [comment]
I have an error above, it should be 0x80000 - 0x40000000 (0x40000000 is the translation, 0x80000 is the internal AXI address).

Today I connected an AXI GPIO to XDMA AXI Lite and the address translation seems to work as I understand it:
- AXI GPIO is at 0x4000_2000 (Range 128)
- XDMA PCIe to AXI translation: 0x4000_0000
```
xsdb% mwr 0x40002000 1                                                                                     
xsdb% mrd 0x40002000                                                                                       
40002000:   00000001
sudo ./reg_rw /dev/xdma0_user 0x2000 h
...
Read 16-bit value at address 0x2000 (0x7f251cb3b000): 0x0001
```
So with XDMA PCIe to AXI translation set to 0x40000000, 0x40000000 must be the **lowest** AXI address, accessible from /dev/xdma0_user device, because Its PCIe address will be 0x0. 

On the AXI SMC (connected to the DDR), I have another JTAG with address width 64-bit, because the DDR is at 0x200000000 (above the 32-bit address range).
I did:
`sudo ./dma_to_device   --verbose --device /dev/xdma0_h2c_0 --address 0x200000000 --size 4294967296 -f   DATA_4G.raw` 
It works (reads back) via the XDMA  xdma0_c2h_0
Then I try via JTAG:
```
xsdb% mrd 0x200000000                                                                                      
       200000000:   DEC0DEE3
```
I implemented URAM at 0xC0000000 to see whether only DDR is affected and couldn't read it on the JTAG as well. Probably I didn't implement properly the JTAG.

**Comment by mwrnd** [comment]
I understand your confusion about the offset. It caused issues for me as well which is why I added it to my notes. I made an [attempt to improve them](https://github.com/mwrnd/notes/commit/f99b892e5bca0e76d424ead64aea95dcbc11f5a6). I don't use the [offset in the 4GB ADIT demo as it is unnecessary](https://github.com/mwrnd/innova2_4gb_adit_xdma_ddr4_demo/blob/a85cd90a4fe67ac133c389c1ed4419852d56c9e2/innova2_xdma_ddr4_test.c#L396) and confusing but I believe anyone using XDMA should be aware of it.

I will make an effort to test JTAG on my 4GB ADIT board today.

**Comment by AGenchev** [comment]
I read your notes, I like it. 
I understand the rationale behind it like if there is a soft-core processor, which has its [peripherals in a sequence at some address range](https://en.wikipedia.org/wiki/Memory-mapped_I/O_and_port-mapped_I/O) like `0x7001000`, `0x7002000`, `0x7003000`, then the offset should be larger than the highest peripheral address so it prevents PCIe access to the the peripherals of the soft-core. And it seems there are additional requirements - probably to be aligned at 1MB.

**Comment by mwrnd** [comment]
I tried `xsdb` on the [`innova2_4gb_adit_xdma_ddr4_demo` bitstream](https://github.com/mwrnd/innova2_4gb_adit_xdma_ddr4_demo/releases/tag/v0.1) and only 2 `JTAG2AXI` targets show up. I can turn the D18 LED on or off with target `4` but nothing works with target `3`.

![Only 2 JTAG2AXI Show Up](https://github.com/mwrnd/innova2_4gb_adit_xdma_ddr4_demo/assets/38073881/4745a085-2178-44d1-9378-6efe02876f06)

This would make sense if the JTAG ID Width were 1-bit (2 options) but I [set it to 4](https://github.com/mwrnd/innova2_4gb_adit_xdma_ddr4_demo/blob/a85cd90a4fe67ac133c389c1ed4419852d56c9e2/innova2_4gb_adit_xdma_ddr4_demo.tcl#L395).

![JTAG-to-AXI Defaults to ID Width of 1](https://github.com/mwrnd/innova2_4gb_adit_xdma_ddr4_demo/assets/38073881/f430963b-7eae-4ac9-a810-0e52390649bf)

When I access the board using Hardware Monitor I see two JTAGs and SYSMON.

![Hardware Monitor JTAG-AXI](https://github.com/mwrnd/innova2_4gb_adit_xdma_ddr4_demo/assets/38073881/3ebd9a51-462c-4650-beac-f52c06afb871)

I re-implemented the project with both JTAG-to-AXI blocks set to 2-bit ID Width and **AXI4** as the Protocol, *NOT* AXI4Lite and now at least all three JTAG2AXI show up but I still cannot access any of the `M_AXI` peripherals.

With the [innova2_xdma_demo](https://github.com/mwrnd/innova2_xdma_demo#test-axi-blocks-over-jtag) project I am able to access all the `M_AXI` peripherals.

![xsdb JTAG2AXI](https://github.com/mwrnd/innova2_4gb_adit_xdma_ddr4_demo/assets/38073881/612b9f57-cfde-4ae9-b358-5992cce36ee9)

The relevant difference in the two projects is the source of the JTAG-to-AXI block clocks and resets. The `aresetn` signal used by the `M_AXI` peripherals should also be used for the JTAG-to-AXI block. I intended to be able to use JTAG to access the peripherals when XDMA is in reset but that is not possible as XDMA in reset would cause all the `M_AXI` peripherals to be in reset. I need to simplify the design and update the DDR4 projects. To proceed with your project you can add DDR4 to the [`innova2_xdma_demo`](https://github.com/mwrnd/innova2_xdma_demo) project and set the JTAG-to-AXI Block ID Widths to >=2 and the protocol to AXI4.

**Comment by AGenchev** [comment]
Thanks, I'll make the experiment hopefully soon and respond whether it worked. 
My JTAG AXI ID widths were 2. Protocol was AXI4 for both JTAGs;
The clock I was using was derived from axi_aclk from XDMA block via clock wizard (100 MHz) and fed to both AXI smart connects (Lite & AXI4 from XDMA) so it should synchronize, but ...
I wanted to use JTAG to test the registers of the IP blocks and whether MMapped I/O over XDMA changes them.

**Comment by mwrnd** [comment]
I have been running tests but no luck. DDR4 seems to disable the JTAG-to-AXI block.

**Comment by mwrnd** [comment]
With only JTAG-to-AXI and DDR4:

![DDR4 Block Diagram](https://github.com/mwrnd/innova2_4gb_adit_xdma_ddr4_demo/assets/38073881/148f30d7-6eb1-4e29-bde8-db79ccb9a6a3)

It almost works as expected:

![xsdb with JTAG-to-DDR4](https://github.com/mwrnd/innova2_4gb_adit_xdma_ddr4_demo/assets/38073881/c64a0211-9871-481e-a70d-d2040cffb607)

If there are both DDR4 and XDMA blocks in an AXI network the JTAG-to-AXI fails:

![xsdb with JTAG DDR4 XDMA](https://github.com/mwrnd/innova2_4gb_adit_xdma_ddr4_demo/assets/38073881/23dee2b0-81b5-48c3-a476-77ffe631ed98)

I will be removing it from my projects and adding a note about this. Since you discovered this, would you like to take the lead on this and ask about it on the [Xilinx Community Forums](https://support.xilinx.com/s/topic/0TO2E000000YKXyWAO/memory-interfaces-and-noc?language=en_US)? I would suggest the question be something like "*JTAG-to-AXI JTAG2AXI fails when XDMA and DDR4 are in the same AXI Network*".

**Comment by AGenchev** [comment]
O.K., thanks again,  I did it [here](https://support.xilinx.com/s/question/0D54U00007yu2FHSAY/jtag2axi-fails-when-xdma-and-ddr4-are-in-the-same-axi-network?language=en_US). Haven't attached image of the block design yet, because my Vivado computer is now busy recovering a failing 5TB HDD under another OS installation (multi-boot).

**Comment by mwrnd** [comment]
The JTAG Issue has a thread on the Xilinx Forum: [JTAG2AXI fails when XDMA and DDR4 are in the same AXI Network](https://support.xilinx.com/s/question/0D54U00007yu2FHSAY/jtag2axi-fails-when-xdma-and-ddr4-are-in-the-same-axi-network?language=en_US). XDMA and JTAG-to-AXI have different [Endianness](https://en.wikipedia.org/wiki/Endianness).

The [innova2_xdma_opencapi](https://github.com/mwrnd/innova2_xdma_opencapi) demo project and the related notes in [embeddedsw AXI IIC over XDMA](https://github.com/mwrnd/notes/tree/main/embeddedsw_AXI_IIC_over_XDMA) are an example of `M_AXI_LITE` memory-mapping and PCIe-to-AXI Translation Offset use.
